# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'

- job: Test
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
