# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

jobs:
- job: Build
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'

- job: Test
  steps:
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
